### ISSUE TITLE
Client crashes when failing to communicate with the mailtm api

### ISSUE THREAD

**Issue by VikasRana** [CarloDePieri/pymailtm#9]
```console
New account created and copied to clipboard: hushedpoultry7@arxxwalls.com


Waiting for new messages...
Traceback (most recent call last):
  File "c:\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python39\Scripts\pymailtm.exe\__main__.py", line 7, in <module>
  File "c:\python39\lib\site-packages\pymailtm\cli.py", line 29, in init
    MailTm().monitor_new_account(force_new=args.new_account)
  File "c:\python39\lib\site-packages\pymailtm\pymailtm.py", line 181, in monitor_new_account
    account.monitor_account()
  File "c:\python39\lib\site-packages\pymailtm\pymailtm.py", line 74, in monitor_account
    new_msg = self.wait_for_message()
  File "c:\python39\lib\site-packages\pymailtm\pymailtm.py", line 66, in wait_for_message
    while len(self.get_messages()) == start:
  File "c:\python39\lib\site-packages\pymailtm\pymailtm.py", line 39, in get_messages
    for message_data in r.json()["hydra:member"]:
  File "c:\python39\lib\site-packages\requests\models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "c:\python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "c:\python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by CarloDePieri** [comment]
Apparently #8 exacerbated an underlying problem with repeated requests to the mailtm api (they could even have lowered the threshold or it could be dynamic, I have no way of knowing that).
Getting around it will require introducing some artificial delay... I don't like this but we will have to make do for now.

This also exposed another issue with pymailtm client, that should be more tolerant when the mailtm api fails and therefore should keep trying.

I'll have a fix out soon.
